name=RailwaySignal
version=1.0.0
author=izzumhdh
maintainer=izzumhdh
sentence=Railway crossing warning signal library.
paragraph=Blinking LEDs and active buzzer warning system for railway crossing simulation.
category=Signal Input/Output
architectures=*